containerhosts:
  host1: &host1
    ip: 192.168.1.48
    port: 3288
  host2: &host2
    ip: 192.168.1.49
    port: 3288
containerdefault: &containerdefault
  mask: 16
  gateway: 10.0.0.100
  dns: 10.0.0.1
  domain: endor.lab
  bridge: br2
  host: *host1
  volumes: &defaultvolumes
    defvol1:defvol1
containers:
  config2:
    <<: *containerdefault
    ip: 10.0.0.201
    image: config
    volumes:
    - *defaultvolumes
    - test:test
    - test2:test2
    state:
  config3:
    <<: *containerdefault
    ip: 10.0.0.202
    image: config
    volumes:
    - *defaultvolumes
    - test:test
    - test2:test2
    host: *host2
    state:
